language: node_js
node_js:
  - "11"

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

before_install:
  - npm update

install:
  - npm ci

script:
  - npm run test:coverage
