/* Did you remember to change ./ActionTypes.js? */

export enum ActionTypes {
  AutoplayerStateUpdate = 'AutoplayerStateUpdate',
  Bookmark = 'Bookmark',
  Debug = 'Debug',
  InkContainersRegistration = 'InkContainersRegistration',
  InkContainersStateInit = 'InkContainersStateInit',
  InkContainersStateUpdate = 'InkContainersStateUpdate',
  InkContainersUnregistration = 'InkContainersUnregistration',
  PassageNavigation = 'PassageNavigation',
  PassageReady = 'PassageReady',
  PassageTime = 'PassageTime',
  SoundManagerGroupStateUpdate = 'SoundManagerGroupStateUpdate',
  SoundManagerSoundStateUpdate = 'SoundManagerSoundStateUpdate',
  SoundManagerStateUpdate = 'SoundManagerStateUpdate',
  SoundsLoaded = 'SoundsLoaded',
  StoryEnd = 'StoryEnd',
  StoryLoaded = 'StoryLoaded',
  StoryOptionsDialogVisible = 'StoryOptionsDialogVisible',
  StoryReset = 'StoryReset',
  StoryRequiresFullRerender = 'StoryRequiresFullRerender',
  StoryRewind = 'StoryRewind',
  StoryState = 'StoryState',
  StoryStateLoad = 'StoryStateLoad',
  StoryStateSave = 'StoryStateSave',
  StoryStateSaveDelete = 'StoryStateSaveDelete',
  StoryStateSaveRegistryInit = 'StoryStateSaveRegistryInit',
}
