import * as fs from 'fs-extra';
import {
  paths,
} from '../paths';
import {
  compile,
} from 'handlebars';
import {
  warn,
} from 'colorful-logging';

// Makes the config variables available in index.html.
export function getTemplatingData(config) {
  const {
    fontsToLoad,
    subsetFont,
  } = config;

  const fontFaceObserver = compile(
    fs.readFileSync(paths.fontFaceObserverTemplate, 'utf8'),
  );

  let fontLoader = '';
  if (fontsToLoad) {
    let subsetFontConditionalStatement =
      `  loadFullFonts(true).then(\n` +
      `    console.log.bind(console),\n` +
      `    console.error.bind(console),` +
      `  );`;

    if (subsetFont) {
      subsetFontConditionalStatement =
        `  var subset = new FontFaceObserver('${subsetFont.fromFamily} Subset');\n` +
        `  /* Load full fonts even if the subset fails. Do not allow longer than 500ms. */\n` +
        `  subset.load(null, 500).then(\n` +
        `  function () { loadFullFonts(true); },\n` +
        `  function (err) {\n` +
        `    console.error('Subset loading encountered an error:', err);\n` +
        `    loadFullFonts(false);\n` +
        `  },\n` +
        `);`;
    }

    fontLoader = compile(
      fs.readFileSync(paths.fontLoaderTemplate, 'utf8'),
      {
        data: {
          fontsToLoad,
          subsetFontConditionalStatement,
        },
      },
    );
  }

  let fontLoaderStyle = '';
  try {
    fontLoaderStyle = fs.readFileSync(paths.fontAutogeneratedStyle, 'utf8');
  } catch (err) {
    warn('An error was encountered accessing the autogenerated font loader ' +
         'style file. Your fonts may not work as expected. Please fix the ' +
         'error and rebuild.');
    warn(err);
  }

  const stringifiedConfig = Object.keys(config).reduce((ret, key) => {
    if (typeof config[key] === 'object') {
      ret[key] = JSON.stringify(config[key]);
    } else {
      ret[key] = config[key];
    }

    return ret;
  }, {})

  return {
    ...stringifiedConfig,
    fontFaceObserver,
    fontLoader,
    fontLoaderStyle,
  };
}
