// Do not link to this module from the config, the browser context, or any
// non-Node context.

import * as fs from 'fs-extra';
import * as path from 'path';

// Make sure any symlinks in the project folder are resolved:
// https://github.com/facebook/create-react-app/issues/637
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = (relativePath) => path.resolve(appDirectory, relativePath);

// Do not import this property in the config, the browser context, or any
// non-Node context.
export const paths = {
  moduleFileExtensions: [
    'css',
    'js',
    'json',
    'jsx',
    'mjs',
    'ts',
    'tsx',
  ],

  appBuild: resolveApp('build-web'),
  appIndex: resolveApp('src/index.tsx'),
  appNodeModules: resolveApp('node_modules/'),
  appPackageJson: resolveApp('package.json'),
  appPath: resolveApp('.'),
  appPublic: resolveApp('public/'),
  appSrc: resolveApp('src/'),
  appTsConfig: resolveApp('tsconfig.json'),
  acceleratorConfig: resolveApp('accelerator.config.js'),
  fontAutogeneratedStyle: resolveApp('public/fonts/autogenerated/fontface-autogen.css'),
  bundles: resolveApp('bundles/'),
  fontFaceObserverTemplate: resolveApp('templates/fontFaceObserver.hbs'),
  fontsAutogenerationDir: resolveApp('public/fonts/autogenerated/'),
  fontsDir: resolveApp('public/fonts/'),
  fontLoaderTemplate: resolveApp('templates/fontLoader.hbs'),
  footers: resolveApp('footers/'),
  headers: resolveApp('headers/'),
  htmlTemplate: resolveApp('templates/index.hbs'),
  imagePreloaderTemplate: resolveApp('templates/imagePreloader.hbs'),
  indexHtml: resolveApp('build-web/index.html'),
  inkMutators: resolveApp('ink-mutators/'),
  passages: resolveApp('passages/'),
  plugins: resolveApp('plugins/'),
  proxySetup: resolveApp('src/setupProxy.ts'),
  renderers: resolveApp('renderers/'),
  storyOptions: resolveApp('options/'),
  testsSetup: resolveApp('src/setupTests.ts'),
  eslintConfig: resolveApp('.eslintrc.js'),
};
