import {
  error,
} from 'colorful-logging';
import * as fs from 'fs-extra';
import {
  getAutogeneratedFileWarningText,
} from './functions/getAutogeneratedFileWarningText';
import {
  getAuthoredAssetObjectDefinitions,
} from './functions/getAuthoredAssetObjectDefinitions';
import {
  getAuthoredImportsMetadata,
} from './functions/getAuthoredImportsMetadata';
import {
  getHotReloadAcceptor,
} from './functions/getHotReloadAcceptor';
import * as path from 'path';
import {
  scrapeAssets,
} from './functions/scrapeAssets';
import {
  setUnhandledRejectionEvent,
} from './functions/setUnhandledRejectionEvent';

setUnhandledRejectionEvent();

const authoredStoryOptionsDir = path.join(__dirname, '..', 'options');

(async () => {
  try {
    const files = await scrapeAssets(authoredStoryOptionsDir);

    const {
      importPaths,
      imports,
      registry,
    } = getAuthoredImportsMetadata(files);
  
    const manifestStr =
      getAutogeneratedFileWarningText() +
      '\nimport { IStoryOptionManifestItem } from \'../src/storyOptions/IStoryOptionManifestItem\';\n\n' +
      imports.join('\n') +
      '\n\nconst manifest: readonly IStoryOptionManifestItem[] = [\n' +
      getAuthoredAssetObjectDefinitions(files).join('\n') +
      '\n];\n\n' +
      'export default manifest;\n\n' + 
      `export const registry = ${JSON.stringify(registry)}\n\n` +
      getHotReloadAcceptor(importPaths) +
      '\n';

    const manifestPath = path.join(authoredStoryOptionsDir, 'options-manifest.ts');
    await fs.writeFile(manifestPath, manifestStr);
  } catch (err) {
    error(err);
    process.exit(1);
  }
})();
